import type {
  Application,
  City,
  Job,
  JobType,
  Review,
  Store,
  User,
} from "./types";

export const seedCities: City[] = [
  { id: "madrid", name_zh: "马德里", name_es: "Madrid", region: "Comunidad de Madrid" },
  { id: "barcelona", name_zh: "巴塞罗那", name_es: "Barcelona", region: "Cataluña" },
];

export const seedJobTypes: JobType[] = [
  { id: "cashier", name_zh: "收银员", name_es: "Cajero/a", icon: "💰" },
  { id: "clerk", name_zh: "店员/导购", name_es: "Dependiente/a", icon: "🛍️" },
  { id: "waiter", name_zh: "服务员", name_es: "Camarero/a", icon: "🍽️" },
  { id: "chef", name_zh: "厨师", name_es: "Cocinero/a", icon: "👨‍🍳" },
  { id: "kitchen_helper", name_zh: "帮厨/传菜", name_es: "Ayudante de cocina", icon: "🍳" },
  { id: "stocker", name_zh: "理货员", name_es: "Reponedor/a", icon: "📦" },
  { id: "delivery", name_zh: "送货员", name_es: "Repartidor/a", icon: "🛵" },
  { id: "manager", name_zh: "店长/主管", name_es: "Encargado/a", icon: "🗝️" },
];

export const seedUsers: User[] = [
  { id: "u_emp_hualian", role: "employer", phone: "+34600100001", wechat: "hualian_boss", name: "陈老板", locale: "zh", email: "hualian.boss@example.com", created_at: "2026-01-10T09:00:00Z" },
  { id: "u_emp_jinlong", role: "employer", phone: "+34600100002", wechat: "jinlong_mgr", name: "李经理", locale: "zh", email: "jinlong.mgr@example.com", created_at: "2026-01-12T09:00:00Z" },
  { id: "u_emp_reina", role: "employer", phone: "+34600100003", wechat: null, name: "王姐", locale: "zh", email: "reina.sushi@example.com", created_at: "2026-02-01T09:00:00Z" },
  { id: "u_emp_oriental", role: "employer", phone: "+34600100004", wechat: "oriental_super", name: "张总", locale: "zh", email: "oriental.super@example.com", created_at: "2026-01-20T09:00:00Z" },
  { id: "u_emp_modanueva", role: "employer", phone: "+34600100005", wechat: null, name: "刘老板", locale: "es", email: "moda.nueva@example.com", created_at: "2026-03-05T09:00:00Z" },
  { id: "u_emp_longmen", role: "employer", phone: "+34600100006", wechat: "longmen_bar", name: "赵老板", locale: "zh", email: "longmen.bar@example.com", created_at: "2026-02-18T09:00:00Z" },
  { id: "u_seek_1", role: "seeker", phone: "+34600200001", wechat: "xiaoyu_2026", name: "小宇", locale: "zh", email: "xiaoyu@example.com", created_at: "2026-04-01T09:00:00Z" },
  { id: "u_seek_2", role: "seeker", phone: "+34600200002", wechat: null, name: "阿芳", locale: "zh", email: "afang@example.com", created_at: "2026-04-03T09:00:00Z" },
  { id: "u_seek_3", role: "seeker", phone: "+34600200003", wechat: "leo_zhang", name: "张磊", locale: "zh", email: "leizhang@example.com", created_at: "2026-04-10T09:00:00Z" },
  { id: "u_seek_4", role: "seeker", phone: "+34600200004", wechat: null, name: "美美", locale: "es", email: "meimei@example.com", created_at: "2026-05-02T09:00:00Z" },
  { id: "u_seek_5", role: "seeker", phone: "+34600200005", wechat: "chenchen88", name: "陈晨", locale: "zh", email: "chenchen@example.com", created_at: "2026-05-15T09:00:00Z" },
];

export const seedStores: Store[] = [
  {
    id: "store_hualian",
    owner_user_id: "u_emp_hualian",
    name_zh: "华联百元店",
    name_es: "Bazar Todo a Cien Hualian",
    city: "madrid",
    district: "Usera",
    address: "Calle de Marcelo Usera 45, Madrid",
    category: "百元店",
    cover_image: "/seed/store-hualian.jpg",
    photos: ["/seed/store-hualian-1.jpg", "/seed/store-hualian-2.jpg"],
    verification_status: "verified",
    verified_at: "2026-02-01T10:00:00Z",
    rating_avg: 4.5,
    rating_count: 23,
  },
  {
    id: "store_jinlong",
    owner_user_id: "u_emp_jinlong",
    name_zh: "金龙中餐馆",
    name_es: "Restaurante Chino Jinlong",
    city: "madrid",
    district: "Tetuán",
    address: "Calle de Bravo Murillo 120, Madrid",
    category: "中餐馆",
    cover_image: "/seed/store-jinlong.jpg",
    photos: ["/seed/store-jinlong-1.jpg"],
    verification_status: "verified",
    verified_at: "2026-02-05T10:00:00Z",
    rating_avg: 4.2,
    rating_count: 41,
  },
  {
    id: "store_reina_sushi",
    owner_user_id: "u_emp_reina",
    name_zh: "皇后自助寿司",
    name_es: "Sushi Buffet La Reina",
    city: "barcelona",
    district: "Eixample",
    address: "Carrer d'Aragó 300, Barcelona",
    category: "自助寿司",
    cover_image: "/seed/store-reina.jpg",
    photos: [],
    verification_status: "pending",
    verified_at: null,
    rating_avg: 0,
    rating_count: 0,
  },
  {
    id: "store_oriental",
    owner_user_id: "u_emp_oriental",
    name_zh: "东方超市",
    name_es: "Supermercado Oriental",
    city: "barcelona",
    district: "Sant Martí",
    address: "Carrer de la Selva de Mar 30, Barcelona",
    category: "超市",
    cover_image: "/seed/store-oriental.jpg",
    photos: ["/seed/store-oriental-1.jpg", "/seed/store-oriental-2.jpg"],
    verification_status: "verified",
    verified_at: "2026-01-25T10:00:00Z",
    rating_avg: 4.6,
    rating_count: 67,
  },
  {
    id: "store_modanueva",
    owner_user_id: "u_emp_modanueva",
    name_zh: "新潮服装店",
    name_es: "Tienda de Ropa Moda Nueva",
    city: "madrid",
    district: "Chueca",
    address: "Calle de Fuencarral 80, Madrid",
    category: "服装店",
    cover_image: "/seed/store-modanueva.jpg",
    photos: [],
    verification_status: "unverified",
    verified_at: null,
    rating_avg: 0,
    rating_count: 0,
  },
  {
    id: "store_longmen",
    owner_user_id: "u_emp_longmen",
    name_zh: "龙门酒吧",
    name_es: "Bar Long Men",
    city: "barcelona",
    district: "Raval",
    address: "Carrer del Raval 12, Barcelona",
    category: "酒吧",
    cover_image: "/seed/store-longmen.jpg",
    photos: [],
    verification_status: "rejected",
    verified_at: null,
    rating_avg: 3.1,
    rating_count: 9,
  },
];

export const seedJobs: Job[] = [
  {
    id: "job_1",
    store_id: "store_hualian",
    title_zh: "百元店收银员",
    title_es: "Cajero/a para bazar todo a cien",
    job_type: "cashier",
    city: "madrid",
    district: "Usera",
    salary_min: 1300,
    salary_max: 1500,
    salary_period: "month",
    headcount: 2,
    schedule: "周一至周六 10:00-20:00，轮休一天",
    live_in: false,
    meals_included: false,
    language_required: "基础西语",
    residence_required: "prefer",
    description_zh: "负责收银、理货、店内基础维护，欢迎有经验者优先。",
    description_es: "Caja, reposición y mantenimiento básico de la tienda. Se valora experiencia previa.",
    status: "active",
    published_at: "2026-08-01T08:00:00Z",
    expires_at: "2026-11-01T08:00:00Z",
    views: 312,
  },
  {
    id: "job_2",
    store_id: "store_hualian",
    title_zh: "百元店理货员",
    title_es: "Reponedor/a para bazar todo a cien",
    job_type: "stocker",
    city: "madrid",
    district: "Usera",
    salary_min: 9,
    salary_max: 10,
    salary_period: "hour",
    headcount: 1,
    schedule: "周二至周日 09:00-14:00（兼职）",
    live_in: false,
    meals_included: false,
    language_required: "不要求",
    residence_required: "none",
    description_zh: "上货、补货、库存整理，兼职时间灵活。",
    description_es: "Recepción de mercancía, reposición y orden de almacén. Horario a tiempo parcial flexible.",
    status: "active",
    published_at: "2026-08-15T08:00:00Z",
    expires_at: "2026-11-15T08:00:00Z",
    views: 156,
  },
  {
    id: "job_3",
    store_id: "store_jinlong",
    title_zh: "中餐馆服务员",
    title_es: "Camarero/a para restaurante chino",
    job_type: "waiter",
    city: "madrid",
    district: "Tetuán",
    salary_min: 1400,
    salary_max: 1600,
    salary_period: "month",
    headcount: 3,
    schedule: "周三至周一 12:00-16:00, 19:00-23:00，周二休息",
    live_in: true,
    meals_included: true,
    language_required: "基础西语",
    residence_required: "none",
    description_zh: "负责点餐、上菜、收台，提供员工宿舍与三餐。",
    description_es: "Toma de pedidos, servicio de mesas y recogida. Alojamiento y comidas incluidos.",
    status: "active",
    published_at: "2026-07-20T08:00:00Z",
    expires_at: "2026-10-20T08:00:00Z",
    views: 498,
  },
  {
    id: "job_4",
    store_id: "store_jinlong",
    title_zh: "中餐馆帮厨/传菜",
    title_es: "Ayudante de cocina para restaurante chino",
    job_type: "kitchen_helper",
    city: "madrid",
    district: "Tetuán",
    salary_min: 1300,
    salary_max: 1450,
    salary_period: "month",
    headcount: 2,
    schedule: "周三至周一 11:30-16:00, 18:30-23:00，周二休息",
    live_in: true,
    meals_included: true,
    language_required: "不要求",
    residence_required: "none",
    description_zh: "配合厨师备菜、传菜，包吃住，适合新手。",
    description_es: "Apoyo en cocina y servicio de platos. Comida y alojamiento incluidos, ideal para principiantes.",
    status: "active",
    published_at: "2026-08-05T08:00:00Z",
    expires_at: "2026-11-05T08:00:00Z",
    views: 271,
  },
  {
    id: "job_5",
    store_id: "store_jinlong",
    title_zh: "中餐馆厨师",
    title_es: "Cocinero/a para restaurante chino",
    job_type: "chef",
    city: "madrid",
    district: "Tetuán",
    salary_min: 2000,
    salary_max: 2600,
    salary_period: "month",
    headcount: 1,
    schedule: "周三至周一 11:00-16:00, 18:00-23:00，周二休息",
    live_in: true,
    meals_included: true,
    language_required: "不要求",
    residence_required: "prefer",
    description_zh: "熟悉中餐炒菜，3年以上经验优先，包吃住。",
    description_es: "Cocina china, se valora 3+ años de experiencia. Comida y alojamiento incluidos.",
    status: "paused",
    published_at: "2026-06-10T08:00:00Z",
    expires_at: "2026-09-10T08:00:00Z",
    views: 623,
  },
  {
    id: "job_6",
    store_id: "store_reina_sushi",
    title_zh: "自助寿司服务员",
    title_es: "Camarero/a para sushi buffet",
    job_type: "waiter",
    city: "barcelona",
    district: "Eixample",
    salary_min: 1350,
    salary_max: 1500,
    salary_period: "month",
    headcount: 2,
    schedule: "周二至周日 12:30-16:00, 19:30-23:30，周一休息",
    live_in: false,
    meals_included: true,
    language_required: "基础西语",
    residence_required: "prefer",
    description_zh: "自助餐厅服务与收台，包工作餐。",
    description_es: "Servicio de sala en buffet de sushi. Comida de personal incluida.",
    status: "active",
    published_at: "2026-08-20T08:00:00Z",
    expires_at: "2026-11-20T08:00:00Z",
    views: 189,
  },
  {
    id: "job_7",
    store_id: "store_reina_sushi",
    title_zh: "自助寿司帮厨",
    title_es: "Ayudante de cocina para sushi buffet",
    job_type: "kitchen_helper",
    city: "barcelona",
    district: "Eixample",
    salary_min: 8.5,
    salary_max: 9.5,
    salary_period: "hour",
    headcount: 1,
    schedule: "周二至周六 10:00-15:00（兼职）",
    live_in: false,
    meals_included: true,
    language_required: "不要求",
    residence_required: "none",
    description_zh: "协助后厨备料，兼职优先应届/学生。",
    description_es: "Apoyo en preparación de cocina. Ideal para estudiantes o recién llegados.",
    status: "active",
    published_at: "2026-09-01T08:00:00Z",
    expires_at: "2026-12-01T08:00:00Z",
    views: 87,
  },
  {
    id: "job_8",
    store_id: "store_oriental",
    title_zh: "超市收银员",
    title_es: "Cajero/a de supermercado",
    job_type: "cashier",
    city: "barcelona",
    district: "Sant Martí",
    salary_min: 1400,
    salary_max: 1550,
    salary_period: "month",
    headcount: 3,
    schedule: "轮班制，周末双休不固定",
    live_in: false,
    meals_included: false,
    language_required: "基础西语",
    residence_required: "required",
    description_zh: "负责收银结算，需能出示有效居留证明。",
    description_es: "Caja y cobros. Se requiere residencia legal en vigor.",
    status: "active",
    published_at: "2026-08-10T08:00:00Z",
    expires_at: "2026-11-10T08:00:00Z",
    views: 402,
  },
  {
    id: "job_9",
    store_id: "store_oriental",
    title_zh: "超市理货员",
    title_es: "Reponedor/a de supermercado",
    job_type: "stocker",
    city: "barcelona",
    district: "Sant Martí",
    salary_min: 1300,
    salary_max: 1450,
    salary_period: "month",
    headcount: 2,
    schedule: "周一至周五 07:00-15:00",
    live_in: false,
    meals_included: false,
    language_required: "不要求",
    residence_required: "none",
    description_zh: "早班理货补货，体力工作，包工装。",
    description_es: "Reposición en turno de mañana. Trabajo físico, uniforme incluido.",
    status: "active",
    published_at: "2026-08-25T08:00:00Z",
    expires_at: "2026-11-25T08:00:00Z",
    views: 234,
  },
  {
    id: "job_10",
    store_id: "store_oriental",
    title_zh: "超市店长/主管",
    title_es: "Encargado/a de supermercado",
    job_type: "manager",
    city: "barcelona",
    district: "Sant Martí",
    salary_min: 2200,
    salary_max: 2800,
    salary_period: "month",
    headcount: 1,
    schedule: "周一至周六，弹性排班",
    live_in: false,
    meals_included: false,
    language_required: "流利西语",
    residence_required: "required",
    description_zh: "统筹门店日常运营与人员排班，需管理经验。",
    description_es: "Gestión diaria de la tienda y turnos del personal. Se requiere experiencia previa.",
    status: "active",
    published_at: "2026-07-01T08:00:00Z",
    expires_at: "2026-10-01T08:00:00Z",
    views: 519,
  },
  {
    id: "job_11",
    store_id: "store_modanueva",
    title_zh: "服装店导购员",
    title_es: "Dependiente/a de tienda de ropa",
    job_type: "clerk",
    city: "madrid",
    district: "Chueca",
    salary_min: 1250,
    salary_max: 1400,
    salary_period: "month",
    headcount: 2,
    schedule: "周一至周六 10:00-14:00, 17:00-21:00",
    live_in: false,
    meals_included: false,
    language_required: "基础西语",
    residence_required: "prefer",
    description_zh: "导购、陈列、库存盘点，形象气质佳优先。",
    description_es: "Atención al cliente, escaparate e inventario.",
    status: "draft",
    published_at: "2026-09-20T08:00:00Z",
    expires_at: null,
    views: 0,
  },
  {
    id: "job_12",
    store_id: "store_modanueva",
    title_zh: "服装店收银员",
    title_es: "Cajero/a de tienda de ropa",
    job_type: "cashier",
    city: "madrid",
    district: "Chueca",
    salary_min: 1250,
    salary_max: 1350,
    salary_period: "month",
    headcount: 1,
    schedule: "周二至周日 11:00-19:00",
    live_in: false,
    meals_included: false,
    language_required: "基础西语",
    residence_required: "none",
    description_zh: "负责收银与简单退换货处理。",
    description_es: "Caja y gestión básica de devoluciones.",
    status: "filled",
    published_at: "2026-06-15T08:00:00Z",
    expires_at: "2026-09-15T08:00:00Z",
    views: 145,
  },
  {
    id: "job_13",
    store_id: "store_longmen",
    title_zh: "酒吧服务员",
    title_es: "Camarero/a de bar",
    job_type: "waiter",
    city: "barcelona",
    district: "Raval",
    salary_min: 10,
    salary_max: 12,
    salary_period: "hour",
    headcount: 2,
    schedule: "周四至周日 21:00-03:00（夜班）",
    live_in: false,
    meals_included: true,
    language_required: "基础西语",
    residence_required: "none",
    description_zh: "夜班吧台与场地服务，含小费分成。",
    description_es: "Servicio de barra y sala en turno de noche. Reparto de propinas incluido.",
    status: "active",
    published_at: "2026-08-28T08:00:00Z",
    expires_at: "2026-11-28T08:00:00Z",
    views: 96,
  },
  {
    id: "job_14",
    store_id: "store_longmen",
    title_zh: "酒吧导购/收银",
    title_es: "Dependiente/a y caja de bar",
    job_type: "clerk",
    city: "barcelona",
    district: "Raval",
    salary_min: 1300,
    salary_max: 1400,
    salary_period: "month",
    headcount: 1,
    schedule: "周三至周日 18:00-01:00",
    live_in: false,
    meals_included: false,
    language_required: "基础西语",
    residence_required: "none",
    description_zh: "吧台收银与简单迎宾接待。",
    description_es: "Caja de barra y recepción básica de clientes.",
    status: "closed",
    published_at: "2026-05-01T08:00:00Z",
    expires_at: "2026-08-01T08:00:00Z",
    views: 210,
  },
];

export const seedReviews: Review[] = [
  {
    id: "review_1",
    store_id: "store_hualian",
    seeker_user_id: "u_seek_1",
    rating: 5,
    comment: "老板人很好，工资准时发，同事也友善。",
    created_at: "2026-05-10T12:00:00Z",
  },
  {
    id: "review_2",
    store_id: "store_jinlong",
    seeker_user_id: "u_seek_2",
    rating: 4,
    comment: "包吃住条件不错，就是周末比较忙。",
    created_at: "2026-06-02T12:00:00Z",
  },
  {
    id: "review_3",
    store_id: "store_oriental",
    seeker_user_id: "u_seek_3",
    rating: 5,
    comment: "超市管理规范，签合同交社保，很靠谱。",
    created_at: "2026-06-20T12:00:00Z",
  },
  {
    id: "review_4",
    store_id: "store_longmen",
    seeker_user_id: "u_seek_4",
    rating: 2,
    comment: "经常临时改排班，沟通不太顺畅。",
    created_at: "2026-07-05T12:00:00Z",
  },
  {
    id: "review_5",
    store_id: "store_jinlong",
    seeker_user_id: "u_seek_5",
    rating: 4,
    comment: "厨房干净，师傅愿意带新人。",
    created_at: "2026-07-18T12:00:00Z",
  },
];

export const seedApplications: Application[] = [
  {
    id: "app_1",
    job_id: "job_1",
    seeker_user_id: "u_seek_1",
    status: "submitted",
    message: "我有半年超市收银经验，可以立即上岗。",
    contact_revealed: false,
    created_at: "2026-09-10T09:00:00Z",
    updated_at: "2026-09-10T09:00:00Z",
  },
  {
    id: "app_2",
    job_id: "job_3",
    seeker_user_id: "u_seek_2",
    status: "viewed",
    message: "会西语基础沟通，餐馆服务员做过一年。",
    contact_revealed: false,
    created_at: "2026-09-08T09:00:00Z",
    updated_at: "2026-09-09T10:00:00Z",
  },
  {
    id: "app_3",
    job_id: "job_8",
    seeker_user_id: "u_seek_3",
    status: "contacted",
    message: "有西班牙长期居留，随时可以面试。",
    contact_revealed: true,
    created_at: "2026-09-05T09:00:00Z",
    updated_at: "2026-09-07T15:30:00Z",
  },
  {
    id: "app_4",
    job_id: "job_10",
    seeker_user_id: "u_seek_4",
    status: "hired",
    message: "有3年超市管理经验，带过10人团队。",
    contact_revealed: true,
    created_at: "2026-08-20T09:00:00Z",
    updated_at: "2026-09-01T11:00:00Z",
  },
  {
    id: "app_5",
    job_id: "job_5",
    seeker_user_id: "u_seek_5",
    status: "rejected",
    message: "做过中餐厨房帮厨两年，想尝试炒锅。",
    contact_revealed: false,
    created_at: "2026-08-15T09:00:00Z",
    updated_at: "2026-08-25T14:00:00Z",
  },
];
